language: node_js
node_js:
- node
deploy:
  provider: heroku
  api_key:
    secure: yhgIONC4I6G9mqXBpOaoTlb2Pg1UCBxX7Sn1AaGCiUPav8eDWptACKpYWwy5UUb/pMA5+R9c8KdupnfQCPqYcenHxSlEryX6t1NqBx+Vq8qxxNZE7o4bLguzaHEZ4KXYmKRYJh/G2XLAsN7oVu/6LaZMiyBxHQte7qMoPoMNHpg+LgSqz4JNJnGMRohIlW66a4XPBZzj2/uRGz5ykmjaRuvUlMS7gsdmOTDIpnSakyNbKjEisBUqRjVf/CF5xzX0WN4r7qv/1r/6IY0YquCg86T7vsiBuHiFHaY2TtaUL0pHtkln6xXaT/QaQaZPnbbJQMd+cRIxt5b/AW10CT9r532xgS0uiJ0f9FtgfAm4pyF7HxSd61HIhAAQlhML300YRHTu6Yu5R1k910x5nVjvK704QkwPF38Hd6HAh1+aiDygUPzm66L/wBt5PRYi095fg7N03iAdF8eyJqeQ7CjqA8JfqZeSwU9FaIl6/piJz26+vdBcGZ2i0Zy4CWIbNiqromeUMYX1XFfQM48AXACHvGtQy4S00BniFLMVRPcLzBHpw3XAyv6D0siDysD/snrmN4p6dH08pq8x8gymxlHGlNkojHBhes+5f8NCg2wX5fPRf0J8Mx0tmE1wfrrALkk+GmfKG+j1lqmFFLmWtp6BSh5eLcqPBRPJPqbDXi7rxmE=
  app: serveAPI
  on:
    repo: junkaiii/serveAPI
